// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

// --------------------------------------------------------------------------
// Interfaces for the three snarkjs-generated Groth16 verifier contracts.
// Each verifier is deployed separately and registered here via setVerifiers().
// The actual Verifier.sol files are auto-generated by snarkjs from your circuits.
// --------------------------------------------------------------------------

interface IVerifier {
    function verifyProof(
        uint[2]    calldata _pA,
        uint[2][2] calldata _pB,
        uint[2]    calldata _pC,
        uint[]     calldata _pubSignals
    ) external view returns (bool);
}

// --------------------------------------------------------------------------
// Main contract
// --------------------------------------------------------------------------

contract CredentialSBT is ERC721, Ownable {

    // ERC-5192 events
    event Locked(uint256 tokenId);
    event Unlocked(uint256 tokenId);

    function locked(uint256 tokenId) external view returns (bool) {
        require(_credentials[tokenId].exists, "Token does not exist");
        return true;
    }

    function supportsInterface(bytes4 interfaceId) public view virtual override returns (bool) {
        return interfaceId == 0xb45a3c0e || super.supportsInterface(interfaceId);
    }

    // ------------------------------------------------------------------
    // Credential storage (unchanged from your current version)
    // ------------------------------------------------------------------

    uint256 private _tokenIdCounter;

    struct Credential {
        string  metadataUri;
        bytes32 metadataHash;
        uint256 issueDate;
        bool    exists;
        bool    isRevoked;
    }

    mapping(uint256 => Credential) private _credentials;
    mapping(address => uint256[])  private _studentTokens;

    string public institutionName;

    event CredentialIssued(address indexed student, uint256 indexed tokenId, string metadataUri, bytes32 metadataHash, uint256 issueDate);
    event CredentialRevoked(address indexed student, uint256 indexed tokenId, uint256 revokedAt);

    // ------------------------------------------------------------------
    // ZKP verifier addresses
    // Each points to a separate deployed Groth16 verifier contract.
    // Set after deployment via setVerifiers().
    // ------------------------------------------------------------------

    IVerifier public gpaVerifier;        // circuit: prove GPA >= threshold
    IVerifier public degreeVerifier;     // circuit: prove degree is in approved set
    IVerifier public existenceVerifier;  // circuit: prove valid non-revoked credential exists

    event VerifiersSet(address gpa, address degree, address existence);

    // ------------------------------------------------------------------
    // ZKP proof events — emitted so the frontend/backend can index them
    // ------------------------------------------------------------------

    event GpaProofVerified(address indexed student, uint256 indexed tokenId, uint256 threshold, bool result);
    event DegreeProofVerified(address indexed student, uint256 indexed tokenId, bool result);
    event ExistenceProofVerified(address indexed student, bool result);

    // ------------------------------------------------------------------
    // Constructor
    // ------------------------------------------------------------------

    constructor(string memory _institutionName) ERC721("Academic Credential", "CRED") Ownable(msg.sender) {
        institutionName  = _institutionName;
        _tokenIdCounter  = 1;
    }

    // ------------------------------------------------------------------
    // Register the three verifier contracts (call once after deployment)
    // ------------------------------------------------------------------

    function setVerifiers(
        address _gpaVerifier,
        address _degreeVerifier,
        address _existenceVerifier
    ) external onlyOwner {
        require(_gpaVerifier       != address(0), "Invalid GPA verifier");
        require(_degreeVerifier    != address(0), "Invalid degree verifier");
        require(_existenceVerifier != address(0), "Invalid existence verifier");

        gpaVerifier       = IVerifier(_gpaVerifier);
        degreeVerifier    = IVerifier(_degreeVerifier);
        existenceVerifier = IVerifier(_existenceVerifier);

        emit VerifiersSet(_gpaVerifier, _degreeVerifier, _existenceVerifier);
    }

    // ------------------------------------------------------------------
    // Credential lifecycle (unchanged)
    // ------------------------------------------------------------------

    function issueCredential(
        address student,
        string  memory metadataUri,
        bytes32 metadataHash
    ) external onlyOwner returns (uint256) {
        require(student != address(0),             "Invalid student address");
        require(bytes(metadataUri).length > 0,     "Metadata URI cannot be empty");
        require(metadataHash != bytes32(0),        "Metadata hash cannot be empty");

        uint256 tokenId = _tokenIdCounter++;
        _safeMint(student, tokenId);

        _credentials[tokenId] = Credential(metadataUri, metadataHash, block.timestamp, true, false);
        _studentTokens[student].push(tokenId);

        emit CredentialIssued(student, tokenId, metadataUri, metadataHash, block.timestamp);
        emit Locked(tokenId);

        return tokenId;
    }

    function revokeCredential(uint256 tokenId) external onlyOwner {
        require(_credentials[tokenId].exists,     "Credential does not exist");
        require(!_credentials[tokenId].isRevoked, "Credential already revoked");

        address student = ownerOf(tokenId);
        _credentials[tokenId].isRevoked = true;
        _burn(tokenId);

        emit CredentialRevoked(student, tokenId, block.timestamp);
    }

    // ------------------------------------------------------------------
    // Standard verification (unchanged)
    // ------------------------------------------------------------------

    function verifyCredential(address student, uint256 tokenId)
        external view
        returns (bool valid, bool revoked, string memory uri, bytes32 hash)
    {
        Credential memory cred = _credentials[tokenId];
        require(cred.exists, "Credential does not exist");
        require(_ownerOf(tokenId) == student || cred.isRevoked, "Token not owned by student");

        revoked = cred.isRevoked;
        uri     = cred.metadataUri;
        hash    = cred.metadataHash;
        valid   = !revoked && ownerOf(tokenId) == student;
    }

    // ------------------------------------------------------------------
    // ZKP verification functions
    //
    // Each function receives a Groth16 proof (pA, pB, pC) and the
    // public signals for that circuit, then delegates to the relevant
    // verifier contract. Private inputs (actual GPA, actual degree, etc.)
    // are NEVER passed here — they stay off-chain inside the proof.
    //
    // Public signals per circuit:
    //
    //   GPA threshold:
    //     pubSignals[0] = credentialHash  (links proof to a specific token)
    //     pubSignals[1] = threshold        (the minimum GPA being claimed, e.g. 300 for 3.00)
    //
    //   Degree membership:
    //     pubSignals[0] = credentialHash
    //     pubSignals[1] = degreeSetRoot    (Merkle root of the approved degree set)
    //
    //   Credential existence:
    //     pubSignals[0] = nullifier        (unique value derived from the credential; prevents double-use)
    //     pubSignals[1] = contractAddress  (ensures the proof was made for THIS contract)
    // ------------------------------------------------------------------

    // Prove: GPA >= threshold, without revealing the actual GPA.
    function verifyGpaProof(
        uint256        tokenId,
        uint[2]    calldata pA,
        uint[2][2] calldata pB,
        uint[2]    calldata pC,
        uint[]     calldata pubSignals   // [credentialHash, threshold]
    ) external returns (bool) {
        require(address(gpaVerifier) != address(0), "GPA verifier not set");
        require(_credentials[tokenId].exists,        "Credential does not exist");
        require(!_credentials[tokenId].isRevoked,    "Credential is revoked");
        require(pubSignals.length == 2,              "Expected 2 public signals");

        bool result = gpaVerifier.verifyProof(pA, pB, pC, pubSignals);

        emit GpaProofVerified(msg.sender, tokenId, pubSignals[1], result);
        return result;
    }

    // Prove: degree belongs to an approved set (e.g. graduate-level degrees),
    // without revealing which specific degree.
    function verifyDegreeProof(
        uint256        tokenId,
        uint[2]    calldata pA,
        uint[2][2] calldata pB,
        uint[2]    calldata pC,
        uint[]     calldata pubSignals   // [credentialHash, degreeSetRoot]
    ) external returns (bool) {
        require(address(degreeVerifier) != address(0), "Degree verifier not set");
        require(_credentials[tokenId].exists,           "Credential does not exist");
        require(!_credentials[tokenId].isRevoked,       "Credential is revoked");
        require(pubSignals.length == 2,                 "Expected 2 public signals");

        bool result = degreeVerifier.verifyProof(pA, pB, pC, pubSignals);

        emit DegreeProofVerified(msg.sender, tokenId, result);
        return result;
    }

    // Prove: a valid, non-revoked credential exists for this wallet,
    // without revealing any credential details whatsoever.
    function verifyExistenceProof(
        uint[2]    calldata pA,
        uint[2][2] calldata pB,
        uint[2]    calldata pC,
        uint[]     calldata pubSignals   // [nullifier, contractAddress]
    ) external returns (bool) {
        require(address(existenceVerifier) != address(0), "Existence verifier not set");
        require(pubSignals.length == 2,                    "Expected 2 public signals");

        bool result = existenceVerifier.verifyProof(pA, pB, pC, pubSignals);

        emit ExistenceProofVerified(msg.sender, result);
        return result;
    }

    // ------------------------------------------------------------------
    // Read helpers (unchanged)
    // ------------------------------------------------------------------

    function getCredential(uint256 tokenId) external view returns (Credential memory) {
        require(_credentials[tokenId].exists, "Credential does not exist");
        return _credentials[tokenId];
    }

    function tokenURI(uint256 tokenId) public view override returns (string memory) {
        require(_credentials[tokenId].exists, "Token does not exist");
        return _credentials[tokenId].metadataUri;
    }

    function getStudentTokens(address student) external view returns (uint256[] memory) {
        return _studentTokens[student];
    }

    // ------------------------------------------------------------------
    // Soulbound enforcement (unchanged)
    // ------------------------------------------------------------------

    function _update(address to, uint256 tokenId, address auth) internal virtual override returns (address) {
        address from = _ownerOf(tokenId);
        require(from == address(0) || to == address(0), "Soulbound: token is non-transferable");
        return super._update(to, tokenId, auth);
    }

    function approve(address, uint256) public virtual override { revert("Soulbound: token is non-transferable"); }
    function setApprovalForAll(address, bool) public virtual override { revert("Soulbound: token is non-transferable"); }
    function transferFrom(address, address, uint256) public virtual override { revert("Soulbound: token is non-transferable"); }
    function safeTransferFrom(address, address, uint256, bytes memory) public virtual override { revert("Soulbound: token is non-transferable"); }
}
